apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgp-app-policy-suggest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edgp-app-policy-suggest
  template:
    metadata:
      labels:
        app: edgp-app-policy-suggest
    spec:
      containers:
        - name: edgp-app-policy-suggest
          image: public.ecr.aws/q1b5w5y6/edgp-app-policy-suggest:VERSION
          imagePullPolicy: Always
          ports:
            - containerPort: 8092
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_edgp_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: aws_edgp_secret_key_id
            - name: ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: ADMIN_URL
            - name: RULE_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: RULE_URL
            - name: AOSS_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: AOSS_URL
          resources:
           requests:
             cpu: "50m"
             memory: "250Mi"
           limits:
             cpu: "350m"
             memory: "500Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: suggest-k8s-service
spec:
  selector:
    app: edgp-app-policy-suggest
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: NodePort
